export const ADD_DOCUMENT_FILE = "ADD_DOCUMENT_FILE";
export const ADD_EXCEL_FILE = "ADD_EXCEL_FILE";
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const ADD_TEMPLATES = "ADD_TEMPLATES";
export const REMOVE_DOCUMENT_FILE = "REMOVE_DOCUMENT_FILE";
export const CLEAR_FILES = "CLEAR_FILES";
export const SET_FILE_LOADING = "SET_FILE_LOADING";
export const SET_LOADING = "SET_LOADING";
